// Snapshot the plugin's component data into web/lib/registry.generated.json so the
// site is self-contained and deployable from web/ alone (no sibling ../plugin needed
// at Vercel build time). Run locally before deploy; commit the generated JSON.
//
// On Vercel the sibling ../plugin isn't uploaded — this script then no-ops and the
// committed snapshot is used. Single source of truth stays plugin/components/*; this
// is a derived artifact, regenerated by `bun run snapshot` (wired into prebuild).
import fs from "node:fs";
import path from "node:path";

const WEB = path.resolve(import.meta.dirname, "..");
const REPO = path.resolve(WEB, "..");
const COMPONENTS_DIR = path.join(REPO, "plugin", "components");
const MARKETPLACE = path.join(REPO, ".claude-plugin", "marketplace.json");
const CONTRACT = path.join(REPO, "plugin", "spec", "CONTRACT.md");
const OUT = path.join(WEB, "lib", "registry.generated.json");

if (!fs.existsSync(COMPONENTS_DIR)) {
  console.log("[snapshot] ../plugin not present — keeping committed snapshot.");
  process.exit(0);
}

const readJson = (f) => {
  try { return JSON.parse(fs.readFileSync(f, "utf8")); } catch { return null; }
};
const asStr = (v, d = "") => (typeof v === "string" ? v : d);
const asArr = (v) => (Array.isArray(v) ? v.filter((x) => typeof x === "string") : []);
const asObj = (v) => (v && typeof v === "object" && !Array.isArray(v) ? v : {});

function resolveAuthor(raw) {
  if (typeof raw === "string") return raw;
  const o = asObj(raw);
  return asStr(o.github) || asStr(o.name) || asStr(o.email);
}

function readComponent(dir) {
  const cd = path.join(COMPONENTS_DIR, dir);
  const m = readJson(path.join(cd, "component.json"));
  if (!m) return null;
  const requires = asObj(m.requires);
  const caps = asObj(m.capabilities);
  const config = asObj(m.config);
  const configSchema = asObj(config.schema);
  const network = [...new Set([...asArr(requires.network), ...asArr(caps.network)])];
  const secretKey = /(secret|token|api[_-]?key|apikey|password)/i;
  const needsSecrets =
    asArr(requires.env).length > 0 ||
    asArr(caps.env).length > 0 ||
    Object.entries(configSchema).some(
      ([k, f]) => asObj(f).type === "secret" || secretKey.test(k),
    );
  let readme = "";
  const rp = path.join(cd, "README.md");
  if (fs.existsSync(rp)) { try { readme = fs.readFileSync(rp, "utf8"); } catch {} }
  return {
    id: asStr(m.id, dir),
    name: asStr(m.name, asStr(m.id, dir)),
    version: asStr(m.version),
    author: resolveAuthor(m.author),
    description: asStr(m.description),
    type: m.type === "line" ? "line" : "segment",
    runtime: asStr(m.runtime),
    hasFetch: typeof m.fetch === "object" && m.fetch !== null,
    network,
    needsSecrets,
    requires: {
      bin: asArr(requires.bin),
      network: asArr(requires.network),
      macos: asArr(requires.macos),
      env: asArr(requires.env),
    },
    configSchema,
    placement: asObj(m.placement),
    readme,
  };
}

const components = fs
  .readdirSync(COMPONENTS_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => readComponent(e.name))
  .filter(Boolean)
  .sort((a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" }));

// marketplace meta
const raw = readJson(MARKETPLACE) ?? {};
const meta = asObj(raw.metadata);
const ownerObj = asObj(raw.owner);
const marketplace = asStr(raw.name, "claude-statusline");
const plugins = Array.isArray(raw.plugins) ? raw.plugins : [];
const match = plugins.find((p) => asStr(asObj(p).name) === "statusline") ?? plugins[0];
const mp = {
  name: asStr(asObj(match).name, marketplace) || "statusline",
  marketplace,
  description: asStr(asObj(match).description) || asStr(meta.description) || asStr(raw.description) || null,
  version: asStr(asObj(match).version) || asStr(meta.version) || asStr(raw.version) || null,
  owner:
    asStr(ownerObj.name) ||
    asStr(ownerObj.url).split("/").filter(Boolean).pop() ||
    asStr(raw.owner) ||
    null,
};

let contractMd = "";
try { contractMd = fs.readFileSync(CONTRACT, "utf8"); } catch {}

const out = { generatedFrom: "plugin/components", components, marketplace: mp, contractMd };
fs.writeFileSync(OUT, JSON.stringify(out, null, 2) + "\n");
console.log(`[snapshot] wrote ${path.relative(WEB, OUT)} — ${components.length} components, contract ${contractMd.length}B`);
